/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as DiagRouteImport } from './routes/diag'
import { Route as ChangePinRouteImport } from './routes/change-pin'
import { Route as BookRouteImport } from './routes/book'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStaffRouteImport } from './routes/_app.staff'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPurchaseOrdersRouteImport } from './routes/_app.purchase-orders'
import { Route as AppPosRouteImport } from './routes/_app.pos'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppEquipmentRouteImport } from './routes/_app.equipment'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppBookingsRouteImport } from './routes/_app.bookings'
import { Route as AppBayBoardRouteImport } from './routes/_app.bay-board'
import { Route as ApiPublicNewsletterRouteImport } from './routes/api.public.newsletter'
import { Route as ApiPublicContactRouteImport } from './routes/api.public.contact'
import { Route as ApiPublicBookingRouteImport } from './routes/api.public.booking'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagRoute = DiagRouteImport.update({
  id: '/diag',
  path: '/diag',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePinRoute = ChangePinRouteImport.update({
  id: '/change-pin',
  path: '/change-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipmentRoute = AppEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppBayBoardRoute = AppBayBoardRouteImport.update({
  id: '/bay-board',
  path: '/bay-board',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicNewsletterRoute = ApiPublicNewsletterRouteImport.update({
  id: '/api/public/newsletter',
  path: '/api/public/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingRoute = ApiPublicBookingRouteImport.update({
  id: '/api/public/booking',
  path: '/api/public/booking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/change-pin': typeof ChangePinRoute
  '/diag': typeof DiagRoute
  '/healthz': typeof HealthzRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bay-board': typeof AppBayBoardRoute
  '/bookings': typeof AppBookingsRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/equipment': typeof AppEquipmentRoute
  '/inventory': typeof AppInventoryRoute
  '/jobs': typeof AppJobsRoute
  '/leads': typeof AppLeadsRoute
  '/notifications': typeof AppNotificationsRoute
  '/pos': typeof AppPosRoute
  '/purchase-orders': typeof AppPurchaseOrdersRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/api/public/booking': typeof ApiPublicBookingRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/change-pin': typeof ChangePinRoute
  '/diag': typeof DiagRoute
  '/healthz': typeof HealthzRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bay-board': typeof AppBayBoardRoute
  '/bookings': typeof AppBookingsRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/equipment': typeof AppEquipmentRoute
  '/inventory': typeof AppInventoryRoute
  '/jobs': typeof AppJobsRoute
  '/leads': typeof AppLeadsRoute
  '/notifications': typeof AppNotificationsRoute
  '/pos': typeof AppPosRoute
  '/purchase-orders': typeof AppPurchaseOrdersRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/api/public/booking': typeof ApiPublicBookingRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/book': typeof BookRoute
  '/change-pin': typeof ChangePinRoute
  '/diag': typeof DiagRoute
  '/healthz': typeof HealthzRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/bay-board': typeof AppBayBoardRoute
  '/_app/bookings': typeof AppBookingsRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/equipment': typeof AppEquipmentRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/staff': typeof AppStaffRoute
  '/api/public/booking': typeof ApiPublicBookingRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/change-pin'
    | '/diag'
    | '/healthz'
    | '/sitemap.xml'
    | '/bay-board'
    | '/bookings'
    | '/customers'
    | '/dashboard'
    | '/equipment'
    | '/inventory'
    | '/jobs'
    | '/leads'
    | '/notifications'
    | '/pos'
    | '/purchase-orders'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/api/public/booking'
    | '/api/public/contact'
    | '/api/public/newsletter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/change-pin'
    | '/diag'
    | '/healthz'
    | '/sitemap.xml'
    | '/bay-board'
    | '/bookings'
    | '/customers'
    | '/dashboard'
    | '/equipment'
    | '/inventory'
    | '/jobs'
    | '/leads'
    | '/notifications'
    | '/pos'
    | '/purchase-orders'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/api/public/booking'
    | '/api/public/contact'
    | '/api/public/newsletter'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/book'
    | '/change-pin'
    | '/diag'
    | '/healthz'
    | '/sitemap.xml'
    | '/_app/bay-board'
    | '/_app/bookings'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/equipment'
    | '/_app/inventory'
    | '/_app/jobs'
    | '/_app/leads'
    | '/_app/notifications'
    | '/_app/pos'
    | '/_app/purchase-orders'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/staff'
    | '/api/public/booking'
    | '/api/public/contact'
    | '/api/public/newsletter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BookRoute: typeof BookRoute
  ChangePinRoute: typeof ChangePinRoute
  DiagRoute: typeof DiagRoute
  HealthzRoute: typeof HealthzRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicBookingRoute: typeof ApiPublicBookingRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicNewsletterRoute: typeof ApiPublicNewsletterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diag': {
      id: '/diag'
      path: '/diag'
      fullPath: '/diag'
      preLoaderRoute: typeof DiagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-pin': {
      id: '/change-pin'
      path: '/change-pin'
      fullPath: '/change-pin'
      preLoaderRoute: typeof ChangePinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-orders': {
      id: '/_app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipment': {
      id: '/_app/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AppEquipmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookings': {
      id: '/_app/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bay-board': {
      id: '/_app/bay-board'
      path: '/bay-board'
      fullPath: '/bay-board'
      preLoaderRoute: typeof AppBayBoardRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/newsletter': {
      id: '/api/public/newsletter'
      path: '/api/public/newsletter'
      fullPath: '/api/public/newsletter'
      preLoaderRoute: typeof ApiPublicNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/booking': {
      id: '/api/public/booking'
      path: '/api/public/booking'
      fullPath: '/api/public/booking'
      preLoaderRoute: typeof ApiPublicBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBayBoardRoute: typeof AppBayBoardRoute
  AppBookingsRoute: typeof AppBookingsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEquipmentRoute: typeof AppEquipmentRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppJobsRoute: typeof AppJobsRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPosRoute: typeof AppPosRoute
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBayBoardRoute: AppBayBoardRoute,
  AppBookingsRoute: AppBookingsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEquipmentRoute: AppEquipmentRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppJobsRoute: AppJobsRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPosRoute: AppPosRoute,
  AppPurchaseOrdersRoute: AppPurchaseOrdersRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BookRoute: BookRoute,
  ChangePinRoute: ChangePinRoute,
  DiagRoute: DiagRoute,
  HealthzRoute: HealthzRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicBookingRoute: ApiPublicBookingRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicNewsletterRoute: ApiPublicNewsletterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
